version: "3.9"

services:

  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
    
  automate-backups-to-s3:
    build: automate-backups-to-s3
    image: crissalvarezh/automate-backups-to-s3

  nginx-gunicorn-proxy:
    build: nginx-gunicorn-proxy
    image: crissalvarezh/nginx-gunicorn-proxy
    environment:
      LISTEN_PORT: "8000"
      APP_NAME: "api"
      APP_PORT: "8080"
      STATIC_ROOT: "/vol"
