version: "3.9"

services:

  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
    
  automate-backups-to-s3:
    build: automate-backups-to-s3
    env_file: 
      - automate-backups-to-s3/.env
    volumes:
      - ./mock:/backups/static-files
      - ./logs:/logs
